services:
  api:
    container_name: ai-chat-api
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - type: bind
        source: ./mcp-servers
        target: /app/mcp-servers
    environment:
      - NODE_ENV=production
    networks:
      - default
      - scout-shared
    depends_on:
      - mongodb

  mongodb:
    container_name: ai-chat-mongodb
    volumes:
      - mongo_data:/data/db

  meilisearch:
    container_name: ai-chat-meilisearch

  vectordb:
    container_name: ai-chat-vectordb

  rag_api:
    container_name: ai-chat-rag-api

volumes:
  mongo_data:

networks:
  scout-shared:
    external: true
    name: scout-shared
