services:
  api:
    container_name: scout-quest-api
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - type: bind
        source: ./mcp-servers
        target: /app/mcp-servers
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    container_name: scout-quest-mongodb
    networks:
      - default
      - scout-shared

  meilisearch:
    container_name: scout-quest-meilisearch

  vectordb:
    container_name: scout-quest-vectordb

  rag_api:
    container_name: scout-quest-rag-api

networks:
  scout-shared:
    external: true
    name: scout-shared
